-- CanMo Supabase setup (Auth + tables + RLS)
-- Assumptions:
-- - You are using Supabase Auth (email+password).
-- - Each user owns their own rows (RLS by auth.uid()).
-- - user_id is auto-filled by DEFAULT auth.uid() to avoid client mistakes.

-- Extensions (safe if already enabled)
create extension if not exists "pgcrypto";

-- === meals ===
create table if not exists public.meals (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade default auth.uid(),
  food_name   text not null,
  calories    integer not null,
  quantity    double precision not null default 1,
  unit        text not null default '份',
  meal_type   text not null default 'other',
  date        date not null,
  created_at  timestamptz not null default now()
);

create index if not exists idx_meals_user_date on public.meals (user_id, date);

alter table public.meals enable row level security;

drop policy if exists meals_select_own on public.meals;
create policy meals_select_own on public.meals
for select to authenticated
using (user_id = auth.uid());

drop policy if exists meals_insert_own on public.meals;
create policy meals_insert_own on public.meals
for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists meals_update_own on public.meals;
create policy meals_update_own on public.meals
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists meals_delete_own on public.meals;
create policy meals_delete_own on public.meals
for delete to authenticated
using (user_id = auth.uid());

-- === weight_records ===
create table if not exists public.weight_records (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade default auth.uid(),
  weight      double precision not null,
  date        date not null,
  created_at  timestamptz not null default now(),
  constraint weight_records_user_date_unique unique (user_id, date)
);

create index if not exists idx_weight_user_date on public.weight_records (user_id, date);

alter table public.weight_records enable row level security;

drop policy if exists weight_select_own on public.weight_records;
create policy weight_select_own on public.weight_records
for select to authenticated
using (user_id = auth.uid());

drop policy if exists weight_insert_own on public.weight_records;
create policy weight_insert_own on public.weight_records
for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists weight_update_own on public.weight_records;
create policy weight_update_own on public.weight_records
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists weight_delete_own on public.weight_records;
create policy weight_delete_own on public.weight_records
for delete to authenticated
using (user_id = auth.uid());

-- === goals ===
create table if not exists public.goals (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null references auth.users(id) on delete cascade default auth.uid(),
  daily_calories  integer not null default 1800,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint goals_user_unique unique (user_id)
);

create index if not exists idx_goals_user on public.goals (user_id);

alter table public.goals enable row level security;

drop policy if exists goals_select_own on public.goals;
create policy goals_select_own on public.goals
for select to authenticated
using (user_id = auth.uid());

drop policy if exists goals_insert_own on public.goals;
create policy goals_insert_own on public.goals
for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists goals_update_own on public.goals;
create policy goals_update_own on public.goals
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists goals_delete_own on public.goals;
create policy goals_delete_own on public.goals
for delete to authenticated
using (user_id = auth.uid());

-- === Optional: keep updated_at fresh on updates ===
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists goals_set_updated_at on public.goals;
create trigger goals_set_updated_at
before update on public.goals
for each row
execute function public.set_updated_at();

